# -*- coding: utf-8 -*-
require 'systemu'
require 'tempfile'
require 'colorize'
require 'coderay'

task :default do
  system 'rake -T'
end

desc "latexをhikiに変換する"
task :hiki_all do
  files = Dir.entries('.')
  files.each{|file|
    p file if file.split('.')[1]=='tex'
  }
end

desc "latexをhikiに変換する"
task :to_hiki do
  file=ARGV[1]
  exit if file.split('.')[1]!='tex'
  file_base = File.basename(file,'.tex')
  p source = file_base+'.tex'
  p command = "latex2hiki #{source}"
end

